{{- if eq (include "relayflows.mode" .) "cloudWorker" -}}
{{- if and (not .Values.credentials.existingSecret) .Values.credentials.enrollmentToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "relayflows.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "relayflows.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.existingSecretKey | quote }}: {{ .Values.credentials.enrollmentToken | quote }}
{{- end }}
{{- end }}
