{{- if and (eq (include "relayflows.mode" .) "standalone") (not (include "relayflows.cronEnabled" .)) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "relayflows.jobName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "relayflows.labels" . | nindent 4 }}
spec:
  {{- include "relayflows.standaloneJobSpec" . | nindent 2 }}
{{- end }}
